### ISSUE TITLE
split files md5sum

### ISSUE THREAD

**Issue by javimixet** [cogitas3d/Linux3DCS#2]
Hi Cicero. I'm having problems with the extraction, maybe some file corrupted while downloading (from MEGA). Can you add to the README the md5sum of the 7z.00x split files so that it is posible to identify the problematic part without the need of downloading all of them again? 
These are the md5sum of my downloaded files:
d3a264b6d26c02d59e7ab29cfbbcca6a  Linux3DCS_2.7z.001
57118b301f815c83fb28c7e7f971532e  Linux3DCS_2.7z.002
1a89dc90837305227de1a52366480558  Linux3DCS_2.7z.003
91f36733ca650db7ca59a5c2117e0b9b  Linux3DCS_2.7z.004
3292b3d69951d04cd50ad69884e36f09  Linux3DCS_2.7z.005
724e237155a4fb0aa64cab450e469397  Linux3DCS_2.7z.006

Thanks

**Comment by cogitas3d** [comment]
Hi @javimixet !

Did you use 7zip.org to extract it?

Now you can download it from other ways (my homepage and torrent), can you try it?

A big hug!

**Comment by javimixet** [comment]
Hi @cogitas3d. Do you mean all my downloaded files md5sum are ok and the problem is with the 7z bin that I'm using (lubuntu 16.04 repo)? I'll try with the 7zip.org.
I have slow connection and Mega is the fastest. Direct download or torrent was taking forever, that's why I asked for de checksums, to avoid redownloading all again.
Thanks

**Comment by javimixet** [comment]
Hi @cogitas3d . I've unzipped the split files with p7zip and got a 14,9 GB iso image that gives "unknown file system" error when mounted in grub (loopback loop) or dd to a clean partition in my hd. I've happen to make grub recognize it mounting the iso with Disk Image Mounter (lubuntu 16.04) and copying all files (sudo cp -a *) to clean partition, but it stucks in the booting process.
¿Is 14,9 GB the size of the iso? When I copy the files from the mounted iso the total size is 7GB or so.
