### ISSUE TITLE
Iso errors

### ISSUE THREAD

**Issue by canonex** [cogitas3d/Linux3DCS#3]
Hi,

I'm trying to use the software: I have downloaded the torrent and unzipped the 7zip.
I have 16Gb Linux3DCS_2.iso file.

- If I try to unzip it I get an **utf-8 error**.
- If I try to mount i receive a
 **mount: wrong fs type, bad option, bad superblock on /dev/loop0,
       missing codepage or helper program, or other error** error
- If I try to use it using virtual box I can't boot from media **cannot read from the boot medium**

How to use this iso?
I have verified the integrity of the torrent.

Thank you,
Riccardo

**Comment by cogitas3d** [comment]
Hi @canonex!

1) Did you used 7zip to extract it? http://www.7-zip.org/
2) You have to clone it with dd to use in a flashdrive: `$ sudo dd if=Linux3DCS_2.iso of=/dev/sdX`
3) To use with Virtualbox, please follow this step-by-step tutorial (in Portuguese): https://docs.google.com/document/d/1tvdzRvb6ZHxh0Zf41rkgsvU72RogCFmAt8Zt3I4dCAQ/edit?usp=sharing

A big hug!

**Comment by canonex** [comment]
The problem was the **uefi boot**.
Use the legacy boot.

Thank you,
Riccardo
