### ISSUE TITLE
Minimun pendrive size?

### ISSUE THREAD

**Issue by mauigna06** [cogitas3d/Linux3DCS#6]
What is the least capacity a pendrive must have to use this OS? Is a 16GB pendrive enough or do I need a 32GB pendrive? Thanks

**Comment by cogitas3d** [comment]
Hi @mauigna06 !

16 GB is sufficient.

**Comment by mauigna06** [comment]
I'm sorry to tell you that 16GB pendrives have only 14.4GB of available storage space. Fortunately I was able to change the one I just had bought for a 32GB one
