### ISSUE TITLE
Cannot complete photogrammetry

### ISSUE THREAD

**Issue by canonex** [cogitas3d/Linux3DCS#7]
Hi,

I cannot complete the reconstruction because I receive the following error:
`
...
22:21:02 [App     ] Scene loaded from interface format (206ms):
	25 images (24 calibrated) with a total of 182.88 MPixels (7.62 MPixels/image)
	4109 points, 0 vertices, 0 faces
22:21:02 [App     ] Preparing images for dense reconstruction completed: 25 images (369ms)
22:21:02 [App     ] Selecting images for dense reconstruction completed: 24 images (2ms)
Estimated depth-maps 24 (100%, 19s981ms)           
Filtered depth-maps 24 (100%, 9s953ms)         
Fused depth-maps 16 (66.67%, 3s, ETA 1s)...Segmentation fault (core dumped)
22:21:41 [App     ] Build date: Jun 23 2017, 18:56:25
22:21:41 [App     ] CPU: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
22:21:41 [App     ] RAM: 15.55GB Physical Memory 1000.00MB Virtual Memory
22:21:41 [App     ] OS: Linux 4.10.0-42-generic (x86_64)
22:21:41 [App     ] SSE & AVX compatible CPU & OS detected
22:21:41 [App     ] Command line: -d 6 /tmp/MVS/scene_dense.mvs
22:21:41 [App     ] Build date: Jun 23 2017, 18:56:25
22:21:41 [App     ] CPU: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
22:21:41 [App     ] RAM: 15.55GB Physical Memory 1000.00MB Virtual Memory
22:21:41 [App     ] OS: Linux 4.10.0-42-generic (x86_64)
22:21:41 [App     ] SSE & AVX compatible CPU & OS detected
22:21:41 [App     ] Command line: /tmp/MVS/scene_dense_mesh.mvs
Input mesh  /tmp/MVS/scene_dense_mesh_texture.ply
output mesh  /tmp/MVS/scene_dense_mesh_texture2.obj
Output mask:
vertex normals, wedge tex coords, Loading Plugins:
Current Plugins Dir is: /usr/lib/meshlab/plugins 
Error in XMLFile: filter_measure.xml - line: -1, column: -1 - 
Error in XMLFile: filter_mutualinfo.xml - line: -1, column: -1 - 
Total 227 filtering actions
Total 13 io plugins
Opening a file with extention ply
MeshLabServer: Failed loading of /tmp/MVS/scene_dense_mesh_texture.ply from dir /home/cogitas3d
Mesh scene_dense_mesh_texture.ply loaded has 0 vn 0 fn
No Script to apply.
Failed saving
Mesh /tmp/MVS/scene_dense_mesh_texture.ply saved as /tmp/MVS/scene_dense_mesh_texture2.obj (0 vn 0 fn)
(  0.0001 sec |   0.0001 sec) Importing OBJ '/tmp/MVS/scene_dense_mesh_texture2.obj'...
Progress:   0.00%

Traceback (most recent call last):
  File "/home/cogitas3d/Programs/blender-2.78c-linux-glibc219-x86_64/2.78/scripts/addons/io_scene_obj/__init__.py", line 147, in execute
    return import_obj.load(context, **keywords)
  File "/home/cogitas3d/Programs/blender-2.78c-linux-glibc219-x86_64/2.78/scripts/addons/io_scene_obj/import_obj.py", line 945, in load
    float_func = get_float_func(filepath)
  File "/home/cogitas3d/Programs/blender-2.78c-linux-glibc219-x86_64/2.78/scripts/addons/io_scene_obj/import_obj.py", line 866, in get_float_func
    file = open(filepath, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/MVS/scene_dense_mesh_texture2.obj'

location: /home/cogitas3d/Programs/blender-2.78c-linux-glibc219-x86_64/2.78/scripts/modules/bpy/ops.py:189
...
`

What can cause this error?
If I import files in /tmp/OpenMVG/reconstruction_sequential I do find some interesting point cloud in ply!

Thank you!
Riccardo

**Comment by cogitas3d** [comment]
Hi @canonex !

Please, show me what have inside these two directories:

/tmp/OpenMVG/reconstruction_sequential
/tmp/MVS

**Comment by canonex** [comment]
In **/tmp/OpenMVG/reconstruction_sequential** i have:

Size | Filename
-- | --
22K | 00000000_Resection.ply
36K | 00000001_Resection.ply
49K | 00000002_Resection.ply
60K | 00000003_Resection.ply
71K | 00000004_Resection.ply
75K | 00000005_Resection.ply
83K | 00000006_Resection.ply
99K | 00000007_Resection.ply
108K | 00000008_Resection.ply
110K | 00000009_Resection.ply
110K | cloud_and_poses.ply
277K | colorized.ply
4,4K | initialPair.ply
12K | Reconstruction_Report.html
16K | residuals_histogram.svg
505K | robust.bin
179K | robust_colorized.ply
71K | robust.ply
533K | sfm_data.bin
3,9K | SfMReconstruction_Report.html
3,9K | SfMStructureFromKnownPoses_Report.html

In **/tmp/MVS** I have:

Size | Filename
-- | --
173K | scene.mvs

Do you need a zip with the file contents?

Thank you,
Ricky

**Comment by cogitas3d** [comment]
Hi @canonex !

I saw the error, probably the problem is that the CPU or the memory did not was enought:

`Segmentation fault (core dumped)`

The new version of OrtogOnBlender have SMVS, maybe you can test it.

OpenMVG, OpenMVS, MVE/SMVS e Dicom2Mesh: https://goo.gl/Rqf1T4

Replace $Home/Program/OrtogOnBlender directory and install the last version of addon: https://github.com/cogitas3d/OrtogOnBlender

A big hug!
