### ISSUE TITLE
English and 4k Monitor

### ISSUE THREAD

**Issue by AndreaMonzini** [cogitas3d/Linux3DCS#8]
Hello i'm testing Linux3DCS and it seems to work !

I tried to change language in Xubuntu to english but i cannot find the way.
I also have problem with 4K monitor with Xubuntu, for now i just increased the system font dimension.
But the GUI interface of softwares is very small.

It could useful a Linux distro with english as default language and HiDPI monitor support ( i use GNOME).

Anyway thank you for the great project!

Andrea

**Comment by cogitas3d** [comment]
Hi @AndreaMonzini !

1) About the translation, we are working on this, but we will publish ahead, in the future.
2) About the monitor, you can solve this increasing the DPI resolution on Preferences:

![captura de tela de 2018-03-15 10-49-35](https://user-images.githubusercontent.com/2422483/37467128-d108bccc-2835-11e8-81e8-e4e5f770b586.png)

A big hug!

**Comment by AndreaMonzini** [comment]
hello @cogitas3d, i have already increased DPI in Blender where i use max DPI, the problem is with the
other software like Meshalab or Linux interface.
I do not have problem with OrtogOnBlender translation ( few words to translate) but with general Linux system language.

Anyway thank you for the suggestion and for your work!

**Comment by cogitas3d** [comment]
I found it:

https://unix.stackexchange.com/questions/167794/how-to-change-language-interface-in-xfce

Maybe can help you.

**Comment by AndreaMonzini** [comment]
i will try it ! thank you.
Alternatively i have to learn a bit of Portuguese ;)
